Added rate-limit-table
hirosystems/docs pull request #111
Opened 2022-06-26 07:10 UTC by LakshmiLavanyaKasturi

## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?
2. What was changed?
3. Link to relevant issues?

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [ ] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

2022-06-27 16:11 UTC, sabbyanandan requested changes
@CharlieC3 @deantchi: Do you have any other thoughts to share?

2022-06-27 16:11 UTC, sabbyanandan commented on docs/get-started/stacks-blockchain-api.md
> +|stacks-node-api.mainnet.stacks.co/extended/|500|
Maybe we can sort the endpoint, so all mainnet, testnet and rest all show in an order.

2022-06-27 21:14 UTC, LakshmiLavanyaKasturi commented on docs/get-started/stacks-blockchain-api.md
> +|stacks-node-api.mainnet.stacks.co/extended/|500|
Done. Endpoints are sorted now.

2022-06-27 23:00 UTC, LakshmiLavanyaKasturi commented
@CharlieC3 and @sabbyanandan: Please review my changes and let me know if this PR is good to merge. Thanks.

2022-06-28 13:45 UTC, CharlieC3 commented
@LakshmiLavanyaKasturi Looks like the `mainnet` and no-name URLs are still separated:
https://hiro-systems-docs-ih87bdjs8-blockstack.vercel.app/get-started/stacks-blockchain-api#rate-limiting

I could clarify a bit more. Since URLs like `stacks-node-api.mainnet.stacks.co/extended/` and `stacks-node-api.stacks.co/extended/` point to the same backend, they will always have the same rate-limit configuration in place. So instead of placing them in separate rows, can we place each pairing in one row instead?

2022-06-29 17:14 UTC, LakshmiLavanyaKasturi commented
@CharlieC3 Can you please review now. Thanks!

2022-06-29 18:29 UTC, CharlieC3 commented
@LakshmiLavanyaKasturi Looks like all of the mainnet + no-names are combined in one row, and the testnet URLs combined in another. I'm looking only to pair up the mainnet + no name URLs on similar _paths_. The testnet URLs should have their separate row like before. e.g.
```
stacks-node-api.mainnet.stacks.co/extended/
or
stacks-node-api.stacks.co/extended/
```

```
stacks-node-api.mainnet.stacks.co/rosetta/
or
stacks-node-api.stacks.co/rosetta/
```

etc

2022-06-29 21:47 UTC, CharlieC3 approved these changes
LGTM! :shipit:  Thanks for bearing with me on the changes! 🙏

2022-06-29 21:57 UTC, merged