Added note about Stacks.js starters interactive CLI
hirosystems/docs pull request #121
Opened 2022-07-15 19:22 UTC by LakshmiLavanyaKasturi

Relates to #120. 

Added a note to access Stacks.js starters interactive CLI repository. 

Files updated: 

https://docs.hiro.so/build-apps/overview
https://docs.hiro.so/build-apps/authentication
https://docs.hiro.so/build-apps/transaction-signing
https://docs.hiro.so/build-apps/message-signing
https://docs.hiro.so/build-apps/data-storage
https://docs.hiro.so/build-apps/integrate-stacking
https://docs.hiro.so/build-apps/integrate-stacking-delegation

2022-07-15 19:42 UTC, janniks commented
<img width="395" alt="Screen Shot 2022-07-15 at 15 23 37" src="https://user-images.githubusercontent.com/6362150/179299344-06aaf2fe-5ce1-4c36-830d-d839b30b4065.png">

Not sure this works as intended yet.

Also should we use note/info block to highlight the info and differentiate it from the flow of the page a bit more?

2022-07-15 20:33 UTC, janniks commented
> And we don't want a standalone page like ...

Good point! I hadn't seen that. Maybe there's an option in  docusaurus to hide the includes directory..

2022-07-18 16:06 UTC, LakshmiLavanyaKasturi commented
> +1 to Jannik's comment ^^. I can't see the included MD showing up correctly in the preview.
> 
> And we don't want a standalone page like https://deploy-preview-121--hiro-docs.netlify.app/includes/stacks.js-starters-note to show up in the path. Perhaps there's a different approach in Docusaurus to include content from other pages as "NOTE".
> 
> Not as a top-level text, but the text being encapsulated inside the NOTE like the following example:
> 
> ![image](https://user-images.githubusercontent.com/1562654/179306150-b6e48250-a049-4d68-b4ac-06edb0c7b18b.png)

Docusaurus has a different way from the traditional one that I did earlier. Thanks for the link @janniks. The preview seems as expected now. Please check my changes now. @sabbyanandan and @janniks.

2022-07-18 18:45 UTC, sabbyanandan requested changes

2022-07-18 18:45 UTC, sabbyanandan commented on docs/includes/stacks.js-starters-note.mdx
> +If you're building a frontend application and looking for ways to bootstrap it, you can go to [stacks.js-starters](https://github.com/hirosystems/stacks.js-starters) repo to generate the application
```suggestion
To build a frontend application, you can go to [stacks.js-starters](https://github.com/hirosystems/stacks.js-starters) repo to generate the application with everything automatically assembled for you.
```

2022-07-19 21:51 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: Reworded the intro sentence a little bit. Please review! Thanks.

2022-07-19 22:13 UTC, sabbyanandan approved these changes

2022-07-19 22:39 UTC, merged