Clarinet-left-nav-changes
hirosystems/docs pull request #170
Opened 2022-09-27 20:00 UTC by LakshmiLavanyaKasturi

Clarinet left nav changes. 

Files changed:
- sidebar.js
- docs/clarinet/

Related to https://github.com/hirosystems/docs/issues/138.

2022-09-28 13:49 UTC, obycode requested changes
This is a good start. I added some comments.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/developer-resources.md
> +- node (>=v14.16.0) - Used for git commit hook
Is this correct? Does clarinet have a git commit hook that requires node/npm?

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/faq.md
> +check for rootless docker installation
This content I added into the Google doc was just notes. It needs to be properly re-worded and formatted for a FAQ.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/feature-guides.md
> +title: Feature Guides
I'm a bit unclear on this section, "Feature Guides". This does not seem like the correct content for this section.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/getting-started.md
> +Now that you have installed and built Clarinet, you can create a new project and then populate the project with smart contracts.
Should there be links to the how-tos for creating a new project, add contract, etc. here? This content is not that helpful on its own for a getting started section.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-add-contract.md
> +path = ".requirements"
I don't think these two lines should be included here. I see that this was copied from our README and should be fixed there as well.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-analyse-with-check-checker.md
> +title: Analyse with Check-Checker
```suggestion
title: Analyze with Check-Checker
```
🇺🇸 😄 , but also, for consistency with the rest of the doc.
Perhaps change the filename to match as well.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-check-contract.md
> +For example, the check-checker analysis described below will generate warnings. If there are errors in the code,
> described below

Will this still be accurate in the new layout, or should it be reworded?

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-create-new-project.md
> +phrases and initial balances. Initial balances are in Micro Stacks (microSTX).
> Micro Stacks (microSTX)

I believe the more common way of writing these would be "microstacks (uSTX)"

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-monitor-test-coverage.md
> +You can measure and increase the code coverage by following the steps mentioned [here](https://github.com/hirosystems/clarinet/#measure-and-increase-code-coverage).
Should these steps just be copied inline here instead of linking to another place?

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-test-contract.md
> +## Deploy contracts to Devnet / Testnet / Mainnet
This section seems like it should be on its own page, since deploying is not related to testing.

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/how-to-guides/how-to-monitor-test-coverage.md
> +title: Monitor Test Coverage
Should this just be a section in the `how-to-test-contract.md` file?

2022-09-28 13:49 UTC, obycode commented on docs/clarinet/introduction.md
> +Clarinet is a Clarity runtime packaged as a command line tool, designed to facilitate smart contract understanding, development, testing and deployment. Clarinet consists of a Clarity REPL and a test
Repeating my comment from the other place this paragraph shows up: I think it is a bit outdated and needs to be enhanced to include more recent features. I think this was written in early clarinet days.

2022-10-03 21:31 UTC, sabbyanandan requested changes

2022-10-03 21:31 UTC, sabbyanandan commented on docs/clarinet/introduction.md
> +## What is Clarinet?
For consistency, can we rephrase this to "Clarinet overview"? All products can follow this as a pattern.

2022-10-03 21:31 UTC, sabbyanandan commented on docs/clarinet/developer-resources.md
> +# Contributing to Clarinet
I understand this is copied over from the Clarinet README in Git. But the instructions here refer to "this" repo at a few places, which needs polishing.

2022-10-03 21:31 UTC, sabbyanandan commented on docs/clarinet/faq.md
> +title: FAQ
It'd be better to see FAQs either numbered or indented, so it is clear for the readers. I cannot tell what this section specifically speaks about, also. Perhaps follow a Q+A like format, so we can ask a question and slide in the answer with screenshots?

2022-10-03 21:31 UTC, sabbyanandan commented on docs/clarinet/feature-guides.md
> +title: Feature Guides
+1 to the observation. The helper could be considered a utility, but not a prominent ones like others.

Features could be all the nouns and verbs in Clarinet CLI, which we could describe or point to its CLI-level docs. Debugger is a feature. Devnet (aka: `clarinet integrate`) is another. Deployment plans, etc. 

These are likely captured in how-to's, so we can compose a top-level summary of all the features here or cross-link to relevant sections.

2022-10-03 21:31 UTC, sabbyanandan commented on docs/clarinet/how-to-guides/how-to-install-clarinet.md
> +brew install clarinet
These appear in the s"setting up local environment"; perhaps remove one of these sections altogether. Whichever section comes first in the left-nav (ordering-wise), that wins and the other can be nuked.

2022-10-05 22:01 UTC, sabbyanandan commented on docs/clarinet/faq.md
> +### Question - 1:
Similar to the consolidation and conventions comments, we could follow this Q +A format for all products. Stacks.js structure in FAW looks different compared to this format.

2022-10-05 22:05 UTC, sabbyanandan requested changes

2022-10-05 22:05 UTC, sabbyanandan commented on docs/clarinet/getting-started.md
> +title: Get started with Clarinet
"Get started with Clarinet" or simply "Get started" - let's stick to a convention, please.

2022-10-05 22:05 UTC, sabbyanandan commented on docs/clarinet/developer-resources.md
> +For more information, refer to the following links.
Should these links be grouped under a blog section or similar?

2022-10-07 23:00 UTC, sabbyanandan commented
Addressed in https://github.com/hirosystems/docs/commit/2ac6d6e8c01c18f6b11a197e70467b519bf9e0f5.

2022-10-07 23:00 UTC, closed without merging