Stacks.js nav changes
hirosystems/docs pull request #171
Opened 2022-09-27 22:06 UTC by LakshmiLavanyaKasturi

Stacks.js left nav changes.

Files changed:

sidebar.js
docs/stacks.js/

Related to https://github.com/hirosystems/docs/issues/138.

2022-09-27 22:26 UTC, janniks requested changes
Thanks — Great progress 👏 
I left some notes.

2022-09-27 22:26 UTC, janniks commented on docs/stacks.js/developer-resources.md
> +Common Pitfall: regenerator-runtime
These "Common Pitfall:"s should be individual headings/sections

2022-09-27 22:26 UTC, janniks commented on docs/stacks.js/developer-resources.md
> +# Stacks CLI references
The commons pitfalls shouldn't share a page with the (very) long list of CLI commands. Maybe they make more sense on the FAQ page.

2022-09-27 22:26 UTC, janniks commented on docs/stacks.js/how-to-guides/how-to-add-dependencies.md
> +title: Add dependencies
This document is semi-internal (we can keep it on GitHub, but doesn't need to be on docs.hiro.so)

2022-09-27 22:26 UTC, janniks commented on docs/stacks.js/how-to-guides/how-to-setup-environment.md
> +title: Setup Environment
Similar to "adding dependencies", more internal than necessary for docs.hiro.so

2022-09-27 22:26 UTC, janniks commented on docs/stacks.js/includes/stacks.js-starters-note.mdx
> +:::note
Includes filenames should start with an underscore to not render an additional page.

2022-09-28 13:45 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/developer-resources.md
> +Common Pitfall: regenerator-runtime
Fixed. Made all the Common Pitfall headings H2.

2022-09-28 14:08 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/developer-resources.md
> +# Stacks CLI references
I think references might be a better place. WDYT?

2022-09-28 14:15 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/how-to-guides/how-to-setup-environment.md
> +title: Setup Environment
Done! Moved it out of docs.

2022-09-28 14:23 UTC, janniks commented on docs/stacks.js/developer-resources.md
> +# Stacks CLI references
CLI Reference should be its own file/page. The pitfalls have nothing to do with the CLI.
If it's easier we could phrase the pitfalls more as FAQ/questions. e.g. _"How to fix the `regenerator-runtime` error"_

2022-09-28 16:13 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/includes/stacks.js-starters-note.mdx
> +:::note
Done!

2022-10-03 21:15 UTC, sabbyanandan requested changes

2022-10-03 21:15 UTC, sabbyanandan commented on docs/stacks.js/feature-guides.md
> +Importing & Polyfills
This section, though, it is under "feature guides",  it'd be good to see an explanation of what feature are we describing here and for when it would be useful to devs.

2022-10-03 21:15 UTC, sabbyanandan commented on docs/stacks.js/getting-started.md
> +You can get started with [Stacks.js starters](https://github.com/hirosystems/stacks.js-starters) to help bootstrap frontend applications.
It'd be nice to have a quick explanation of what the starter site can help with, and also replace the URL to https://docs.hiro.so/stacksjs-starters.

2022-10-03 21:15 UTC, sabbyanandan commented on docs/stacks.js/how-to-guides/how-to-authenticate-users-with-connect.md
> +title: Authenticating users
Since the top-level heading of the left nav is "How-To's", we would consider rephrasing the sub nav titles to have a better flow.

Alternatively, you can keep the titles as-is, but change the "How-To's" -> "How-To Guides" for consistency with "Feature Guides" before this.

2022-10-03 21:15 UTC, sabbyanandan commented on docs/stacks.js/stacks.js-overview.md
> +Apps built with the Stacks blockchain give users control over their digital identities, assets, and data.
This is a general purpose pitch, but perhaps don't have to repeated in each product level overview. Perhaps this type of content can be moved to top-level overview section.

2022-10-03 21:15 UTC, sabbyanandan commented on docs/stacks.js/stacks.js-overview.md
> +Unlike most cloud-based apps, they are "decentralized" since they don't depend on any centralized platform, server, or database to function. Rather, they use the Stacks blockchain to authenticate use
This, again, we could move to the general overview and not in each product.

2022-10-03 21:15 UTC, sabbyanandan commented on docs/stacks.js/stacks.js-overview.md
> +This page provides information on how to build such apps using [Stacks.js](https://github.com/blockstack/stacks.js) and other libraries that make integration of the Stacks blockchain easy for front-e
We could expand specifically the Stacks.js' value prop. And that being the SDK with a collection of JS libraries to interact with and transact on Stacks blockchain. The product pages in hiro.so and the product charter can help with more content ideas also.

2022-10-04 19:27 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/developer-resources.md
> +# Stacks CLI references
Moved pitfalls to FAQ's and CLI references to its own page called "references".

2022-10-04 19:27 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/faq.md
> +→ Any supplied post-conditions are always verified, regardless of "mode" (and abort the tx if any supplied PC evaluates to false).
Fixed!

2022-10-04 19:30 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/faq.md
> +#### How to fix the Polyfilling Buffer?
Done!

2022-10-04 19:32 UTC, LakshmiLavanyaKasturi commented on docs/stacks.js/feature-guides.md
> +Importing & Polyfills
I might need some guidance from @janniks here. I will set up some time with him tomorrow.

2022-10-05 21:34 UTC, sabbyanandan requested changes

2022-10-05 21:34 UTC, sabbyanandan commented on docs/stacks.js/faq.md
> +Post-conditions are less a part of clarity (the language), but more a part of transactions.
This section can move up so it serves as an intro before we dive into the bullets. Looks odd to being with bullets.

2022-10-05 21:34 UTC, sabbyanandan commented on docs/stacks.js/faq.md
> +## Post-Conditions (Mode)
What does "(Mode)" in heading signify? Looks odd.

2022-10-05 21:34 UTC, sabbyanandan commented on docs/stacks.js/getting-started.md
> +Stacks.js starters provides a way to start a new JavaScript project using the most common frameworks.
It'd be better make it Stacks.js specific.

```suggestion
[Stacks.js starters](https://docs.hiro.so/stacksjs-starters) provide a quick and easy way to get started with Stacks.js.
```

2022-10-05 21:34 UTC, sabbyanandan commented on docs/stacks.js/getting-started.md
> +The [Stacks.js starters](https://docs.hiro.so/stacksjs-starters) templates help you bootstrap your frontend application.
Perhaps remove this.

2022-10-05 21:34 UTC, sabbyanandan commented on docs/stacks.js/resources/blogs.md
> +title: Blogs
The entirerity of "Developer resources" look minimalistic.

2022-10-05 21:34 UTC, sabbyanandan commented on docs/stacks.js/resources/blogs.md
> +
Maybe add

> We refresh and add more new Stacks.js blogs continuously; to learn more about the new developments, you can retrieve all the blogs with Stacks.js tags through this search criteria under [Hiro blogs](https://www.hiro.so/search?query=stacks.js).

2022-10-05 22:00 UTC, sabbyanandan commented on docs/stacks.js/resources/contact-us.md
> +title: Help us improve
It'd be good to follow the same structure and labeling for all products. In Clarinet PR, I see "Contributing to Clarinet". Let's take this opportunity to consolidate the conventions?

2022-10-06 13:10 UTC, janniks approved these changes
👏

_just some minor notes, we could address these later as well_

2022-10-06 13:10 UTC, janniks commented on docs/stacks.js/developer-resources/videos.md
> +* [Stacks.js starters](https://www.youtube.com/watch?v=SGrbeoCSHs0).
We could look into embedding videos directly in the page

2022-10-06 13:10 UTC, janniks commented on docs/stacks.js/faq.md
> +## Post-Conditions
Should be on the same level as other FAQs (post-condition is not the parent of other items). Also the text above this heading should be a part of the post-condition section

2022-10-07 23:00 UTC, sabbyanandan commented
Addressed in https://github.com/hirosystems/docs/commit/2ac6d6e8c01c18f6b11a197e70467b519bf9e0f5.

2022-10-07 23:00 UTC, closed without merging