Docs re-structure for Clarinet, Stacks-blockchain-api, Stacks.js, Stacks-explorer products
hirosystems/docs pull request #186
Opened 2022-10-06 14:42 UTC by LakshmiLavanyaKasturi

- Re-structured left nav for 4 products.
- Updated Sidebar.js to include nav for all 4 products.
- Updated content based on the latest feature upgrades.

2022-10-06 17:58 UTC, sabbyanandan requested changes
@LakshmiLavanyaKasturi @trichards-hiro: looks pretty good! I commented on a few overlapping sections. And a few other thoughts:

+ many empty pages are in the PR - what is the plan of action? fill them up or leave them as-is?
+ Explorer docs are very minimal; let's follow-up with the product team to assemble some content

2022-10-06 17:58 UTC, sabbyanandan commented on docs/clarinet/developer-resources/blogs.md
> +title: Blogs
A meta comment that applies to all product sections. I like this feedback from @janniks: https://github.com/hirosystems/docs/pull/171#issuecomment-1269998303 — let's please switch the titles to leading caps.

2022-10-06 17:58 UTC, sabbyanandan commented on docs/clarinet/developer-resources/clarinet-discord.md
> +title: Clarinet - discord
Given this is just a link in this page, can we get rid of this page and instead make "Clarinet - discord" a hyperlink on the left-nav directly?

If we do this, we need to apply that change to all products.

2022-10-06 17:58 UTC, sabbyanandan commented on docs/clarinet/faq.md
> +### Question - 1:
I left this comment in the old PR. Either we follow Q + A format for all products or remove the titles entirely. 

Making the question in BOLD probably is sufficient, and no numbering might look cleaner.

2022-10-06 17:58 UTC, sabbyanandan commented on docs/clarinet/how-to-guides/how-to-install-clarinet.md
> +title: Clarinet Installation
Do we need this here? Shouldn't this be already covered in "getting started"?

2022-10-06 17:58 UTC, sabbyanandan commented on docs/stacks-blockchain-api/how-to-guides/how-to-install-stacks-blockchain-api.md
> +Title: Install Stacks Blockchain API
This should be already covered in "getting started", so we can remove it from how-to guide? 

@trichards-hiro

2022-10-06 17:58 UTC, sabbyanandan commented on docs/stacks-explorer/developer-resources/stacks-explorer-discord.md
> +Title: Stacks-Explorer - discord
As said earlier, we can directly make the left-nav item a hyperlink to API's discord channel versus having a new page with just that link. @trichards-hiro

2022-10-06 17:58 UTC, sabbyanandan commented on docs/stacks.js/developer-resources/contribution-guidelines.md
> +title: Contribution guidelines
This can also be a direct link versus having a new page with just this link in the body. @trichards-hiro

2022-10-06 18:05 UTC, sabbyanandan commented
> * Explorer docs are very minimal; let's follow-up with the product team to assemble some content

Pinged: https://hiropbc.slack.com/archives/C03TU42NL05/p1665079443535109?thread_ts=1664488674.033069&cid=C03TU42NL05

2022-10-06 18:45 UTC, LakshmiLavanyaKasturi commented on docs/clarinet/developer-resources/blogs.md
> +title: Blogs
I agree. Done edited for all the products.

2022-10-06 19:18 UTC, LakshmiLavanyaKasturi commented on docs/clarinet/developer-resources/clarinet-discord.md
> +title: Clarinet - discord
Yes, I didn't get a chance this morning to finish this up. Done now! Added hyper-link for all the discord channels for all the products.

2022-10-07 19:47 UTC, janniks commented on docs/stacks-blockchain-api/faqs.md
> +https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/nft/holdings/?limit=200&principal=SP3EQ7FQ8TFXB792P7VAGRXER0YNFMGM1Y8RS69RC is only reporting 49 NFTs; however, the marketplace shows it h
```suggestion
[/extended/v1/tokens/nft/holdings/?limit=200&principal=SP3EQ7FQ8TFXB792P7VAGRXER0YNFMGM1Y8RS69RC](https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/nft/holdings/?limit=200&principal=SP3EQ7FQ8TFXB792P7VAGRXER0YNFMGM1Y8RS69RC) is only reporting 49 NFTs; however, the marketplace shows it has 133 NFTs: 92 NFTs for sale, and 41 NFTs are unlisted,. Why is `/holdings/` not returning all results?
```

I think, when links are raw they might not be parsed correctly.

2022-10-07 19:52 UTC, janniks commented on docs/stacks-blockchain-api/faqs.md
> +Many marketplace contracts are custodial; mmeaning, you do not actually own the NFT, but the marketplace contract does (but it has been marked to your address). This is why the NFT does not appear in
```suggestion
Many marketplace contracts are custodial; meaning, you do not actually own the NFT, but the marketplace contract does (but it has been marked to your address). This is why the NFT does not appear in `/holdings`.
```

2022-10-07 22:06 UTC, sabbyanandan requested changes

2022-10-07 22:06 UTC, sabbyanandan commented on sidebars.js
> +              href: 'https://www.hiro.so/search?query=Explorer',
This should be stacks.js blogs ...

2022-10-07 22:06 UTC, sabbyanandan commented on sidebars.js
> +              label: 'Contribution guidelines',
```suggestion
              label: 'Contribution Guidelines',
```

Let's use this case everywhere

2022-10-07 22:06 UTC, sabbyanandan commented on sidebars.js
> +              href: 'https://www.youtube.com/c/HiroSystems/search?query=Blockchain%20API',
This link appears to not filter videos correctly

2022-10-07 22:50 UTC, sabbyanandan approved these changes
Let's go! 💥

2022-10-07 22:53 UTC, merged