Subnets
hirosystems/docs pull request #205
Opened 2022-10-19 19:22 UTC by LakshmiLavanyaKasturi

Added getting started guide for Subnets. 

Files changed:

- sidebar.js
- subnets/getting-started.md
- subnets/overview.md

Changed introduction -> overview in the Clarinet files to keep the product consistency.

2022-10-19 21:03 UTC, LakshmiLavanyaKasturi commented on docs/subnets/getting-started.md
> +You can get started building subnets using the [subnets-readme](https://github.com/hirosystems/stacks-subnets/blob/master/README.md) documentation.
Had mixed thoughts about it until I pushed the PR. :-) I guess it makes sense to keep the consistency until we solve the duplicating problem. I will change it.

2022-10-31 19:57 UTC, LakshmiLavanyaKasturi commented on docs/subnets/getting-started.md
> +You can get started building subnets using the [subnets-readme](https://github.com/hirosystems/stacks-subnets/blob/master/README.md) documentation.
Changes are pushed to the PR. @sabbyanandan and @trichards-hiro. Please review. Thanks!

2023-02-06 16:19 UTC, kantai requested changes
The `overview.md`, `trust-models.md`, `getting-started.md` content looks fine.

The `how-to-guides`, however, I think don't make sense here: each of these how-to's is actually just a couple steps from the [NFT_USE_CASE.md](https://github.com/hirosystems/stacks-subnets/blob/master/NFT_USE_CASE.md), and the steps all depend on each other, so the how-to's don't make sense by themselves. This could be solved by just making this part of the docs a "NFT use case walkthrough" or similar. Otherwise, the docs will need to be updated so that these things make more sense individually.

But at a high level, the subnets repo is still under active development, and some of this content is likely to need to change. This content all looks directly derived from the MD files in the subnets repo, is it possible to build these doc files from that repo? Or, just ensure that the files are actually identical, so that any updates later are easier?

2023-02-06 19:33 UTC, LakshmiLavanyaKasturi commented
> The `overview.md`, `trust-models.md`, `getting-started.md` content looks good to me.
> 
> The `how-to-guides`, however, I think don't make sense here: each of these how-to's is actually just a couple steps from the [NFT_USE_CASE.md](https://github.com/hirosystems/stacks-subnets/blob/master/NFT_USE_CASE.md), and the steps all depend on each other, so the how-to's don't make sense by themselves. This could be solved by just making this part of the docs a "NFT use case walkthrough" or similar. Otherwise, the docs will need to be updated so that these things make more sense individually.
> 
> But at a high level, the subnets repo is still under active development, and some of this content is likely to need to change. This content all looks directly derived from the MD files in the subnets repo, is it possible to build these doc files from that repo? Or, just ensure that the files are actually identical, so that any updates later are easier?

Thanks for your quick response. I will put together all the how-to's into one guide. 
We recently pushed a plugin that pulls remote content to docs. So, for your question yes we do have the option to pull the content from the Subnet repository to docs without duplication.

2023-02-22 19:11 UTC, saralab commented on docs/subnets/feature-guides/trust-models.md
> +In a fully - trusted model:
In "this fully trusted federated model"

2023-02-27 21:41 UTC, LakshmiLavanyaKasturi commented
Closing this PR as @trichards-hiro will come up with a new PR.

2023-02-27 21:41 UTC, closed without merging