[Stacks 2.1] Add Stacks.js docs
hirosystems/docs pull request #220
Opened 2022-11-10 18:43 UTC by janniks

- added basic thoughts on @stacks/stacking in 2.1
- update some auto-formating and minor fixes

Feel free to take over if you don't like the structure etc.
I can add more content later. Also some of the version numbers etc. aren't final yet

2022-11-17 16:41 UTC, trichards-hiro commented on docs/stacks.js/how-to-guides/how-to-migrate-stacking-to-2.1.md
> +- `StackingClient.getDelegationStatus()` gets the `get-delegation-info` information of the address from a node (readonly contract call)
```suggestion
- `StackingClient.getDelegationStatus()` gets the `get-delegation-info` information of the address from a node (read-only contract call)
```

2022-11-17 16:42 UTC, trichards-hiro commented on docs/stacks.js/how-to-guides/how-to-migrate-stacking-to-2.1.md
> +Previous `@stacks/stacking` releases should automatically switch to the new PoX contract (in Period 3).
```suggestion
Previous `@stacks/stacking` releases should automatically switch to the new PoX contract (in Period 3); however, if you want to use the new methods detailed above, you need to update to `@stacks/stacking` to version >=`6.0.0`.
```

2022-11-17 16:43 UTC, trichards-hiro commented on docs/stacks.js/how-to-guides/how-to-migrate-stacking-to-2.1.md
> +However, if you want to use the new methods detailed above, you need to update to `@stacks/stacking` to a version >=`6.0.0`.
```suggestion
```

2022-12-06 16:00 UTC, saralab commented
@LakshmiLavanyaKasturi : 
Can we include the updated periods for activation and transition for clarity from this blog: https://www.hiro.so/blog/how-the-stacks-2-1-transition-impacts-stacking ?

2022-12-06 18:30 UTC, sabbyanandan requested changes

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +If the contracts you're developing use Clarity 2, you must wait for this epoch to cross before deploying your contracts.
Appears to be an important callout. Perhaps add emphasis or bold or as a NOTE?

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +Clarinet has been updated with new features to work with Stacks 2.1. For more detailed information about these updates, refer to [new features in Clarinet](https://www.hiro.so/blog/meet-4-new-feature
The blog linked here includes new improvements to Clarinet, but aren't entirely Stacks 2.1 specific, though.

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +The endpoints ` /extended/v1/tx/<txid>` and `/extended/v1/contract/<contract-principal>` returns a new property, `clarity_version.`
We could add a statement explaining what this section is about to unpack. Feels odd to jump right into an endpoint w/o any primer.

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +The Stacks 2.1 updates support alternate recipients for coinbase transactions. The `alt_recipient` value is passed in the blockchain transaction, and the API returns a new coinbase `alt_recipient` pr
```suggestion
The Stacks 2.1 updates support alternate recipients for Coinbase transactions. The `alt_recipient` value is passed in the blockchain transaction, and the API returns a new Coinbase `alt_recipient` property on applicable requests; however, if you want to use the latest methods detailed above, you need to update to `@stacks/stacking` to version >=`6.0.0`.
```

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +### PoX2 support for Rosetta API
We use PoX-2 and PoX2 formats; it'd be better to follow a single format for consistency.

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +Mention about three sections below.
Confused about "mention" - copy+paste error?

2022-12-06 18:30 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +### New helper methods
Under each section, let's add a simple description as to what it is about to unpack.

2022-12-13 19:08 UTC, janniks commented on docs/stacks-2.1-upgrades.md
> +title: Migrate Stacking to 2.1
Title should maybe be something more general. The article is not only about "stacking"

2022-12-14 15:34 UTC, LakshmiLavanyaKasturi commented on docs/stacks-2.1-upgrades.md
> +To upgrade your clarinet version, you can refer to [install from a pre-built binary](clarinet/getting-started.md#install-from-a-pre-built-binary) or [install from source using Cargo](clarinet/getting
I don't think so from my earlier conversations. But double-checking with Brice to make sure I don't miss anything.

2022-12-14 16:28 UTC, janniks commented on docs/stacks-2.1-upgrades.md
> +The endpoints [`/extended/v1/tx/<txid>`](/extended/v1/tx/<txid>) and [`/extended/v1/contract/<contract-id>`](https://docs.hiro.so/api#tag/Smart-Contracts/operation/get_contract_by_id) now returns a n
`[`/extended/v1/tx/<txid>`](/extended/v1/tx/<txid>)` this shouldn't be a link or point to something working (like the following link)

2022-12-15 15:52 UTC, LakshmiLavanyaKasturi commented on docs/stacks-2.1-upgrades.md
> +To upgrade your clarinet version, you can refer to [install from a pre-built binary](clarinet/getting-started.md#install-from-a-pre-built-binary) or [install from source using Cargo](clarinet/getting
Brice confirmed that there is no requirement for 2.1 specific upgrade steps

2022-12-15 15:55 UTC, LakshmiLavanyaKasturi commented on docs/stacks-2.1-upgrades.md
> +Clarinet has been updated with new features to work with Stacks 2.1. For more detailed information about these updates, refer to [new features in Clarinet](https://www.hiro.so/blog/meet-4-new-feature
Agreed. Removing this as its not required here.

2022-12-15 15:57 UTC, LakshmiLavanyaKasturi commented on docs/stacks-2.1-upgrades.md
> +The endpoints [`/extended/v1/tx/<txid>`](/extended/v1/tx/<txid>) and [`/extended/v1/contract/<contract-id>`](https://docs.hiro.so/api#tag/Smart-Contracts/operation/get_contract_by_id) now returns a n
Ok. Removing the links per this conversation.

2022-12-15 17:19 UTC, sabbyanandan requested changes

2022-12-15 17:19 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +After installing the latest version of Clarinet, navigate to your project directory and then to `settings/Devnet.toml` (here after referred to as **devnet.toml**).
```suggestion
After installing the latest version of Clarinet, navigate to your project directory and then to `settings/Devnet.toml` (hereafter referred to as **devnet.toml**).
```

2022-12-15 17:19 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +Now that you have a general understanding of Stacks 2.1 and the PoX changes and what to expect let's dive into each product and understand the new features or improvements to the existing features fo
```suggestion
Now that you have a general understanding of Stacks 2.1 and the PoX changes and what to expect, let's dive into each product and understand the new features or improvements to the existing features for Stacks 2.1 upgrade.
```

2022-12-15 17:19 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +New stacks-node will spin up. At Bitcoin block height 102, the chainstate will migrate to epoch 2.05, a network upgrade introduced introduced earlier this year, reducing operations costs. At bitcoin
```suggestion
New stacks-node will spin up. At Bitcoin block height 102, the chainstate will migrate to epoch 2.05, a network upgrade introduced earlier this year, reducing operations costs. At bitcoin block height 106, the chainstate will migrate to epoch 2.1.
```

2022-12-15 17:19 UTC, sabbyanandan commented on docs/stacks-2.1-upgrades.md
> +Stacks 2.1 upgrade for Stacks JS include methods now accepting `poxAddress` in more BTC address formats (P2PKH, P2SH, P2WPKH, P2WSH, P2TR) and new [Stacking](#new-pox-interaction-functions-clarity) a
Stacks.js is the current naming, so let's retain it.

```suggestion
Stacks 2.1 upgrade for Stacks.js include methods now accepting `poxAddress` in more BTC address formats (P2PKH, P2SH, P2WPKH, P2WSH, P2TR) and new [Stacking](#new-pox-interaction-functions-clarity) and [Helper](#new-helper-methods) methods.
```

2022-12-19 17:45 UTC, trichards-hiro approved these changes

2022-12-20 04:37 UTC, merged