new procedures for 6.2.2
hirosystems/docs pull request #239
Opened 2022-12-12 19:39 UTC by deantchi

- deprecating procedures for api 5.x.x
- add new procedures for api 6.x.x

2022-12-13 15:39 UTC, sabbyanandan requested changes

2022-12-13 15:39 UTC, sabbyanandan commented on docs/references/hiro-archiver.md
> +Generating a tsv directly from the Postgres database is the preferred method of obtaining and replaying the tsv for v6.x.x.
Perhaps keep it TSV for consistency all throughout.

```suggestion
Generating a TSV directly from the Postgres database is the preferred method of obtaining and replaying the TSV for v6.x.x.  
```

2022-12-13 15:39 UTC, sabbyanandan commented on docs/references/hiro-archiver.md
> +It is neccessary to restore the Postgres database first, then from the API at startup, exec the following:
```suggestion
It is necessary to restore the Postgres database first, then from the API at startup, run the following command:
```

2023-01-04 18:43 UTC, LakshmiLavanyaKasturi commented
These changes are no longer relevant after the updates from Charlie. Hence closing this PR.

2023-01-04 18:43 UTC, closed without merging