Reuse remote MD files instead of duplicating
hirosystems/docs pull request #250
Opened 2023-01-09 16:51 UTC by LakshmiLavanyaKasturi

## Description

The motivation was to pull remote docs content to the Hiro docs while removing the duplication of content. Added docusaurus plugin to pull the content directly from the product-specific repos.
 

Relates to https://github.com/hirosystems/docs/issues/126.

2023-01-10 17:34 UTC, janniks approved these changes

2023-01-10 23:30 UTC, sabbyanandan requested changes
A few nit-picks. I love the 1000s of lines of Docs-assets that we deleted!

2023-01-10 23:30 UTC, sabbyanandan commented on package.json
> +    "docusaurus-plugin-remote-content": "^3.1.0",
Hypothetic question: The last release (ie: 3.1.0) of this plugin was in April 2022. Should we be concerned about the related dependencies, their security vulnerabilities, and/or the lack of maintenance?

2023-01-10 23:30 UTC, sabbyanandan commented on docusaurus.config.js
> +          // in the plugin's options:
I see commented property repeating and probably can be removed. Also, please take the opportunity to document the properties that we use.

2023-01-10 23:30 UTC, sabbyanandan commented on docusaurus.config.js
> +          sourceBaseUrl: "https://raw.githubusercontent.com/hirosystems/stacks.js/master/docs/how-to-guides/", // the base url for the markdown (gets prepended to all of the documents when fetching)
Curious what would be the procedure for when the branch gets renamed. Let's say we change it from `master` to `main` - would we fail the build on our side or how do we remediate?

2023-01-10 23:30 UTC, sabbyanandan commented on docusaurus.config.js
> +    ["docusaurus-plugin-remote-content",
It'd be good to reformat this file content. The comment sections and the parens if they are pretty printed or similar, it would be easier to read.

2023-01-10 23:31 UTC, sabbyanandan commented
FWIW, I am not sure if this is a problem with the Vercel's preview build, but when I edit a page from the preview, I was hoping to see the source of that file from the product-specific repo and it is instead redirecting me to Hiro's doc repo.

For instance, I clicked "Edit this page" link at the bottom of https://hiro-systems-docs-git-fork-lakshmilavanyakast-982824-blockstack.vercel.app/stacks-blockchain-api/feature-guides/rate-limiting, and that redirected me to https://github.com/hirosystems/docs/edit/main/docs/stacks-blockchain-api/feature-guides/rate-limiting.md — shouldn't this go to the API's repo where the source of this page resides?

2023-01-11 00:05 UTC, janniks commented
I think we might be able to fix the "Edit this page" problem, docusaurus has a feature for it.

2023-01-11 03:09 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +          sourceBaseUrl: "https://raw.githubusercontent.com/hirosystems/stacks.js/master/docs/how-to-guides/", // the base url for the markdown (gets prepended to all of the documents when fetching)
If the branch name changes, we have to update all the respective URL's; else build will fail.

2023-01-11 15:16 UTC, LakshmiLavanyaKasturi commented on package.json
> +    "docusaurus-plugin-remote-content": "^3.1.0",
I saw some latest commits to the [Docusaurus plugin repo](https://github.com/rdilweb/docusaurus-plugin-remote-content), but I see the latest version is 4.0.0. I will investigate how the `yarn add` is picking up  version "docusaurus-plugin-remote-content@3.1.0".

2023-01-13 19:14 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +    ["docusaurus-plugin-remote-content",
done

2023-01-17 06:23 UTC, LakshmiLavanyaKasturi commented on package.json
> +    "docusaurus-plugin-remote-content": "^3.1.0",
there seem to be healthy downloads for the latest plugin from the npm page https://www.npmjs.com/package/docusaurus-plugin-remote-content?activeTab=versions

Its dependencies have not been updated since Sep 2022, which is a little concerning. However, there are 34 open pull requests; some opened as latest as 4 days back. We should revisit this topic in 3 months and check where these are at. For now, i believe it's ok

2023-01-17 06:35 UTC, LakshmiLavanyaKasturi commented
@janniks, there is docusaurus cli mode, which will allow the files only be downloaded at the start of the server and not during runtime. Can we include this plugin and enable files to be downloaded at the beginning rather than runtime?docusaurus-cli will also prevent unnecessary network calls; otherwise, docusaurus-plugin-remote-content will keep making.

2023-01-18 14:45 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +          // in the plugin's options:
I have added the comments for each property we use already.

2023-01-18 21:48 UTC, sabbyanandan commented
@LakshmiLavanyaKasturi: The "Edit this page" still doesn't work for me. FWIW, I am using the preview link from this PR to test it. Other than this, I don't have concerns with the PR.

2023-01-19 15:29 UTC, LakshmiLavanyaKasturi commented
> @LakshmiLavanyaKasturi: The "Edit this page" still doesn't work for me. FWIW, I am using the preview link from this PR to test it. Other than this, I don't have concerns with the PR.

Hi Sabby, sorry. It works now. I realized that Jannik's changes were not pushed to this remote branch earlier.

2023-01-19 22:40 UTC, sabbyanandan commented
@LakshmiLavanyaKasturi: Thanks. The edit links work as expected. 💪🏽

A few general questions:
+ We are pulling assets from upstream repos based on `master` and `main` branches. Will we ever be in a state where any non-production released Docs changes would end up in these branches? I suspect not (such changes would live under `develop` or similar, I think), but it'd be good to double-check.
+ Were we able to verify the GitHub Actions and the automation that will automatically rebuild and deploy the Docs site based on upstream changes? Or will it have to be manually triggered?

2023-01-20 18:57 UTC, sabbyanandan commented
> For your first point, no, unless we configure them in docusaurus.config file, new files will not automatically come.

I realized I wasn't clear in my previous message. I was more interested in understanding whether, in Clarinet, API, or in other repos, would we ever get to a situation where any non-released features or capabilities end up getting pushed to `main` branch? Let's confirm with the product teams, given they may have some automation rules around PR merges and to keep the `main` and `develop` (or other branches) in a synchronized state regularly. Another way said, let's ensure we don't accidentally refresh the Docs site with new features that aren't yet publicly released.

2023-01-20 19:19 UTC, LakshmiLavanyaKasturi commented
> > For your first point, no, unless we configure them in docusaurus.config file, new files will not automatically come.
> 
> I realized I wasn't clear in my previous message. I was more interested in understanding whether, in Clarinet, API, or in other repos, would we ever get to a situation where any non-released features or capabilities end up getting pushed to `main` branch? Let's confirm with the product teams, given they may have some automation rules around PR merges and to keep the `main` and `develop` (or other branches) in a synchronized state regularly. Another way said, let's ensure we don't accidentally refresh the Docs site with new features that aren't yet publicly released.

Sabby, regarding your comment, I can write some guidelines to ensure product teams don't push new features to docs that are not yet ready for external developers/public use.
[1:16](https://hiropbc.slack.com/archives/D03J1J2NTHV/p1674242210852099)
It looks like there is a way to set permissions on project folders https://stackoverflow.com/questions/40567468/give-permissions-on-project-folder-in-github.
We can do this for all the docs folders in product repos to get more visibility on docs changes.

2023-01-20 19:34 UTC, sabbyanandan approved these changes
I am good with the proposed changes. Thank you for doing this! Incredible feat.

2023-01-24 15:20 UTC, merged