Added Stacks Connect link to references
hirosystems/docs pull request #254
Opened 2023-01-11 21:00 UTC by LakshmiLavanyaKasturi

Added stacks_connect link to references.

Updated: Docusaurus config file to include the new link under references.

Relates to https://github.com/hirosystems/docs/issues/129

2023-01-11 21:02 UTC, sabbyanandan requested changes

2023-01-11 21:02 UTC, sabbyanandan commented on docusaurus.config.js
> +                href: 'https://connect.stacks.js.org/modules/_stacks_connect',
Perhaps better to point to https://connect.stacks.js.org; otherwise, looks good!
```suggestion
                href: 'https://connect.stacks.js.org',
```

2023-01-11 23:44 UTC, janniks commented on docusaurus.config.js
> +                href: 'https://connect.stacks.js.org/modules/_stacks_connect',
👍

2023-01-12 00:01 UTC, janniks approved these changes
+1 to @sabbyanandan comment, otherwise good to go 👍

2023-01-12 18:51 UTC, merged