Added epoch changes to stacks 2.1 upgrades
hirosystems/docs pull request #258
Opened 2023-01-17 20:06 UTC by LakshmiLavanyaKasturi

## Description

Added a section in Stacks 2.1 upgrades to include epoch changes.

1. Motivation for change?
- New upgrade
2. What was changed?
- Documentation
3. Link to relevant issues?
4. N/A

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [x] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

2023-01-17 20:43 UTC, obycode requested changes

2023-01-17 20:43 UTC, obycode commented on docs/stacks-2.1-upgrades.md
> +```
I would prefer to have this under a separate `###` heading, maybe "Contract settings", before the "Update Devnet settings" section.

2023-01-17 20:43 UTC, obycode commented on docs/stacks-2.1-upgrades.md
> +If you wish to publish your contracts compatible with Stacks 2.1, you can specify the epoch value by navigating to your project folder and to `clarinet.toml` and updating the below settings.
I think this sentence could be more clear:

In your project's _Clarinet.toml_ file, you can now specify the epoch during which a contract should be deployed, and the Clarity version that it uses. Note that selecting the Clarity version is only available in epoch 2.1 and will be ignored in earlier epochs.

2023-01-20 01:26 UTC, LakshmiLavanyaKasturi commented on docs/stacks-2.1-upgrades.md
> +"In your project's `Clarinet.toml` file, you can now specify the epoch during which a contract should be deployed, and the Clarity version it uses. Note that you may **only** select the Clarity versi
OOps. WIll do. Thanks for the catch!

2023-01-20 11:46 UTC, obycode approved these changes

2023-01-20 15:13 UTC, merged