add api key to sidebar in stacks-blockchain-api,ordinals-api,token-me…
hirosystems/docs pull request #381
Opened 2023-06-14 22:00 UTC by LakshmiLavanyaKasturi

## Description

Add the how-to-use-api-key to all the products : 
1. stacks-blockchain-api
2. ordinals-api
3. token-metadata

## Checklist

- [x] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] New links to files and images were verified
- [x] For fixes/refactors: all existing references were identified and replaced
- [x] [Style guide](https://developers.google.com/style) was reviewed and applied
- [x] Clear code samples were provided
- [x] People were tagged for review

@rafaelcr @sabbyanandan

2023-06-15 16:41 UTC, sabbyanandan requested changes

2023-06-15 16:41 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +There are multiple ways to interact with the API endpoints. However, this document walks you through three ways to make an [API call](https://docs.hiro.so/api#tag/Microblocks/operation/get_microblock
In the preview, this is how it looks:
<img width="858" alt="image" src="https://github.com/hirosystems/docs/assets/1562654/cc3cf2f7-32f8-472d-92e7-7baa8fa57bee">

And it can a bit more clearer.

Maybe:

> There are multiple ways to interact with the API endpoints. In this guide, we will walk through the following approaches with the help of an API endpoint.

2023-06-15 16:41 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +Using Curl, you will pass the API key in an `x-hiro-api-key` header. Use the following command as an example to call the API endpoint `https://api.hiro.so/extended/v1/microblock`.
Since we are including the same guide across 3 different API products, the API endpoint example in use could be confusing in Metadata and Ordinals API guides.

Any way we can parameterize the URL, so a different value can be plugged at Docs' build time for different API guides?

If the above is not possible, maybe we could generalize the URL; something like.. `https://api.hiro.so/ ... ` 

Basically, not a fully qualified Stacks Blockchain API as an example, but just a pattern. If you choose this method, then you may have to update the screenshots, also.

2023-06-22 20:37 UTC, sabbyanandan requested changes

2023-06-22 20:37 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +> The API key is passed in the **header** of your API call and is used only for private use, like server-side applications. This key is not to be exposed or shared.
```suggestion
> The API key is passed in the **header** of your HTTP API request and is used only for private use, like in server-side applications. This key is not to be exposed or shared; if you use the API key in your client-side application (e.g., frontend and browser-based applications), attackers can capture it using the client tools (e.g., browser console) and abuse your API key.
```

2023-06-22 20:37 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +- Typescript function
```suggestion
- Typescript client
```

2023-06-22 20:37 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +You can use the following sample to pass the API key in your function using Typescript.
```suggestion
The following Typescript snippet demonstrates the instantiation of  RESTful HTTP requests with API key.
```

2023-06-22 20:37 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +> **_NOTE:_**
Perhaps this can be a warning instead of note?

2023-06-22 21:23 UTC, sabbyanandan requested changes
**General observation:** When navigating to "Ordinals API -> How-to Guides -> How to use API key" automatically all other references to the "API key" guides expanded, also. 

See: 
![image](https://github.com/hirosystems/docs/assets/1562654/5f0df717-f055-49d5-b138-0664dcf0d334)

2023-06-22 21:23 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +> **_Warning:_**
```suggestion
> :::caution
```

Suggesting the use of caution admonition: https://docusaurus.io/docs/next/markdown-features/admonitions

2023-06-22 21:25 UTC, sabbyanandan commented on docs/api/how-to-use-api-key.md
> +# How to use API Key?
```suggestion
# How to use API Key
```

So that the title is consistent with other how-to guides. Also, the question mark won't show up on the left-nav.

2023-06-22 23:28 UTC, LakshmiLavanyaKasturi commented
> **General observation:** When navigating to "Ordinals API -> How-to Guides -> How to use API key" automatically all other references to the "API key" guides expanded, also.
> 
> See: ![image](https://user-images.githubusercontent.com/1562654/248063643-5f0df717-f055-49d5-b138-0664dcf0d334.png)

I will look into this issue.

2023-06-22 23:31 UTC, merged