Updated docs changelog to use monthly blog post links
hirosystems/docs pull request #397
Opened 2023-07-07 21:42 UTC by LakshmiLavanyaKasturi

- Deleted monthly change log files and updated the sidebar to use the blog post links.
- Relates to https://github.com/hirosystems/docs/issues/384

2023-07-10 22:01 UTC, sabbyanandan requested changes

2023-07-10 22:01 UTC, sabbyanandan commented on sidebars.js
>        label: 'Appendix',
Maybe "Product Changelogs".

2023-07-11 16:49 UTC, sabbyanandan commented
Let's include also the June changelog: https://www.hiro.so/blog/release-roundup-june-2023

2023-07-17 19:01 UTC, LakshmiLavanyaKasturi commented
Closing this PR as we have irrelevant commits added to this branch. The new PR is https://github.com/hirosystems/docs/pull/413.

2023-07-17 19:01 UTC, closed without merging