Added API-try it experience to the Stacks Blockchain API, Ordinals and Token Metadata API's.
hirosystems/docs pull request #419
Opened 2023-07-21 22:26 UTC by LakshmiLavanyaKasturi

- Updated docusaurus config to add plugins and presets to use with the Open API Spec
- Added JSON files to the OpenAPI folder

2023-07-24 20:20 UTC, sabbyanandan commented
WOAH! This is so cool; how did I miss this PR! 👏🏽

2023-07-24 21:31 UTC, LakshmiLavanyaKasturi commented
Using the Preset-Open API, examples are not showing up. I need to investigate that before merging this PR.

2023-07-27 17:57 UTC, rafaelcr commented on openapi/ordinals.json
> +    "version": "v0.1.2"
How will we update these JSON files? This one looks very old

2023-07-28 19:56 UTC, LakshmiLavanyaKasturi commented
Depends on https://github.com/hirosystems/docs/issues/426

2023-07-28 19:56 UTC, LakshmiLavanyaKasturi commented on openapi/ordinals.json
> +    "version": "v0.1.2"
Per conversation https://github.com/hirosystems/docs/issues/426 is created to add JSON files in the remote repos.

2023-08-01 00:07 UTC, LakshmiLavanyaKasturi commented
We want to release this feature without automation of JSON files being pulled from remote API repos to docs for now. So, this feature is ready for release. @sabbyanandan Please review. Thanks!

2023-08-01 13:55 UTC, rafaelcr approved these changes
LGTM

2023-08-01 14:24 UTC, LakshmiLavanyaKasturi commented
Some examples are still not showing up in the Stacks Blockchain API. I am looking into it.

2023-08-01 20:25 UTC, sabbyanandan requested changes

2023-08-01 20:25 UTC, sabbyanandan commented on docusaurus.config.js
> +        sourceBaseUrl:
Can we reformat the whole JS file with a JS formatter, so all these extra spaces and line-breaks can be removed? Maybe also check to the line-width to align with what we follow as a rule for TS/JS files in other projects. That way, things will be easy to read/review.

2023-08-01 20:25 UTC, sabbyanandan commented on docusaurus.config.js
> +   /*  [
It appears we are hard loading the static files instead of resolving from the upstream repos. Is JSON a must for `docusaurus-preset-openapi` to work? Curious.

2023-08-01 20:25 UTC, sabbyanandan commented on docusaurus.config.js
> +        api: {
Can we please move this up, so that Stacks, Ordinals and Metadata API' configs are all together at a single location in the file? I am referring to lines 23-37 ^^.

2023-08-08 07:55 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +   /*  [
@sabbyanandan Here is the issue to address the remaining elements. https://github.com/hirosystems/docs/issues/426.

2023-08-08 08:11 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +        api: {
@sabbyanandan, I prefer it this way. 
The reason being token-metadata-API is defined in the preset, unlike other APIs defined as plugins. Also, this preset has "editUrl({ docPath })," which helps with the "Edit this page" link for all the product docs at the bottom of each doc page. It feels natural to check for this edit  URL at the end of the doc.

Happy to change if the above statement isn't convincing.

2023-08-08 08:25 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +        sourceBaseUrl:
Done.

2023-08-08 08:26 UTC, LakshmiLavanyaKasturi commented
@janniks, Can you please confirm if the docusaurus.config.js file formatting looks good to you? Thanks!

2023-08-09 18:35 UTC, merged

2023-08-09 19:33 UTC, janniks commented on docusaurus.config.js
> +        api: {
Could still try this in the future. I'm not sure why we had one preset in the first working version. Might need a preset to load and then only allows more loading via the plugin section (although I'm not sure any more, so we could try at some point). If it works it works ☺️

2023-08-09 19:33 UTC, janniks commented
Looking good! Happy to see this live! 🚀