Added Algolia configuration to docs
hirosystems/docs pull request #427
Opened 2023-07-28 16:56 UTC by LakshmiLavanyaKasturi

Updated docusaurus config to implement Algolia search.

2023-08-31 17:08 UTC, sabbyanandan requested changes

2023-08-31 17:08 UTC, sabbyanandan commented on package.json
> +    "algolia": "^0.0.0",
Is this the recommended config?

2023-08-31 17:08 UTC, sabbyanandan commented on .gitignore
> +docs/ordinals-api/
Is this required for this PR?

2023-08-31 18:32 UTC, LakshmiLavanyaKasturi commented on .gitignore
> +docs/ordinals-api/
This is unrelated to Algolia, it can be part of a different PR.

2023-08-31 18:36 UTC, LakshmiLavanyaKasturi commented on docusaurus.config.js
> +        'https://deploy-preview-427--docs-hiro.netlify.app': 'https://docs.hiro.so',
Sorry, it was part of the previous implementation of Algolia with Netlify! Removed it from the code now.

2023-09-01 16:27 UTC, LakshmiLavanyaKasturi commented
@eugeniadigon, Please ensure the design and colors match the Hiro org standards.
![image](https://github.com/hirosystems/docs/assets/55154433/cf24268c-b387-4b13-b2ba-f22630cdf9f1)

2023-09-06 23:35 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: I resolved all the comments from you. Hence, merging this PR.

2023-09-06 23:35 UTC, merged