Platform chainhook documentation
hirosystems/docs pull request #431
Opened 2023-08-02 02:33 UTC by LakshmiLavanyaKasturi

Added documentation to create chainhook using Hiro Platform.

2023-08-02 15:41 UTC, sabbyanandan requested changes

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +Chainhook is a powerful feature that enables you to automatically trigger an action based upon a predicate event occurring. To learn more about Chainhook, refer to [Chainhook overview documentation](
```suggestion
Chainhook enables you to automatically trigger an action based upon an event occurring in Stacks, Bitcoin and others. To learn more about Chainhook, refer to [Chainhook overview documentation](https://docs.hiro.so/chainhook/overview).
```

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +**Name**: Select a name of your choice for chainhook.
```suggestion
**Name**: Define a chainhook name of your choice.
```

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +**Chain**: Select the chain between Bitcoin and Stacks to create a chainhook.
```suggestion
**Chain**: Select between Bitcoin and Stacks to create a chainhook.
```

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +**Network**: Choose a network between `mainnet` and `testnet` to run the chainhook node.
```suggestion
**Network**: Choose a network between `mainnet` and `testnet` to observe for events 
```

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +- For *Bitcoin*, the available predicate options are `txid`,`outputs`, `stacks_protocols`.
@BLuEScioN: please verify the choices starting here, and the corresponding text.

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +> _Refer to the following predicate definition documents to understand the available predicates and how to define them._
```suggestion
> _Refer to the following documents to understand the available predicates and how to use them._
```

2023-08-02 15:41 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +Based on the chosen network, the status of the chainhook is updated to **Deployed**.
```suggestion
Based on the chosen network, the respective status columns in the Chainhook list page will be updated to **Deployed**.
```

2023-08-07 18:17 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +- For *Bitcoin*, the available predicate options are `txid`,`outputs`, `stacks_protocols`.
@BLuEScioN Do you have any feedback here?

2023-08-07 20:46 UTC, elenananana requested changes

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +title: Create Chainhook
```suggestion
title: Create a chainhook
```

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +Chainhook enables you to automatically trigger an action based upon an event occurring in Stacks, Bitcoin, and others. To learn more about Chainhook, refer to [Chainhook overview documentation](https
```suggestion
With chainhooks, you can automatically trigger an action  in response to on-chain events on Stacks, Bitcoin, and other Bitcoin layers, enabling you to use IFTT (if_this, then_that) logic to power your applications. To learn more about Chainhook, refer to [Chainhook overview documentation](https://docs.hiro.so/chainhook/overview).
```

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +This guide helps you create a Chainhook using the [Hiro Platform](https://platform.hiro.so/).
```suggestion
This guide helps you create a chainhook using the [Hiro Platform](https://platform.hiro.so/).
```

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +You'll see a navigation bar with two tabs, Contracts, and Chainhook. Select Chainhook to create a new chainhook.
```suggestion
You'll see a navigation bar with two tabs, Contracts, and Chainhooks. Select Chainhooks to create a new chainhook.
```

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +Select the _Create chainhook_ button at the bottom of the screen.
```suggestion
Select the _Create a Chainhook_ button at the bottom of the screen.
```

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +Once you define the fields, you can select **Create chainhook**.
```suggestion
Once you define the fields, you can select **Create a Chainhook**.
```

2023-08-07 20:46 UTC, elenananana commented on docs/platform/create-chainhook.md
> +The right pane navigates to the Projects page with the Chainhook tab open, and you can view the chainhook created.
```suggestion
The right pane navigates to the Projects page with the Chainhooks tab open, and you can view the chainhook created.
```

2023-08-08 08:34 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +title: Create Chainhook
@elenananana, The sidebar is updated based on the title of the doc. So, I will leave this as "Create Chainhook" to keep it consistent with the other sidebar items. 

![image](https://github.com/hirosystems/docs/assets/55154433/49710cbf-6a69-4efc-a9d3-68d4fae171d8)

2023-08-08 14:42 UTC, sabbyanandan requested changes

2023-08-08 14:42 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +With chainhooks, you can automatically trigger an action  in response to on-chain events on Stacks, Bitcoin, and other Bitcoin layers, enabling you to use IFTT (if_this, then_that) logic to power you
```suggestion
With chainhooks, you can automatically trigger an action in response to on-chain events on Stacks, Bitcoin, and other Bitcoin layers, enabling you to use IFTT (if_this, then_that) logic to power your applications. To learn more about Chainhook, refer to [Chainhook overview documentation](https://docs.hiro.so/chainhook/overview).
```

2023-08-08 14:42 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +You'll see a navigation bar with two tabs, Contracts, and Chainhooks. Select _Chainhooks_ to create a new chainhook.
```suggestion
You'll see a navigation bar with two tabs, Contracts, and Chainhook. Select _Chainhook_ to create a new chainhook.
```

2023-08-08 14:42 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +- For *Bitcoin*, the available predicate options are `txid`,`outputs`, `stacks_protocols`.
@BLuEScioN: ping

2023-08-08 14:42 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +You'll see a navigation bar with two tabs, Contracts, and Chainhooks. Select _Chainhooks_ to create a new chainhook.
@elenananana: I am not sure if you caught this, the tab is still referred to as "Chainhooks", and it should be the product/project name, no? Or you would prefer it to be the hooks (in plural)? If the latter, then it needs to be small-C, but it isn't. 

@LakshmiLavanyaKasturi: Let's hold onto this edit until @elenananana confirms.

2023-08-08 14:42 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +The right pane navigates to the Projects page with the Chainhooks tab open, and you can view the chainhook created.
Depending on what happens with @elenananana's feedback on the tab, we may have to correct here and also in the product. cc: @andresgalante

2023-08-08 14:42 UTC, sabbyanandan commented on docs/platform/create-chainhook.md
> +You'll see a navigation bar with two tabs, Contracts, and Chainhooks. Select _Chainhooks_ to create a new chainhook.
cc: @andresgalante @BLuEScioN (please follow the chatter/feedback from @elenananana ^^)

2023-08-08 14:51 UTC, BLuEScioN commented on docs/platform/create-chainhook.md
> +**Then-that**: This action is defaulted to `http_post` to allow the chainhook post events to the URL specified in the below option.
the chainhook to post event

2023-08-08 14:52 UTC, BLuEScioN commented on docs/platform/create-chainhook.md
> +**Decode Clarity Values**: This is enabled by default to help you decode clarity values in your contract.
enabled by default for stacks predicates

2023-08-08 14:53 UTC, BLuEScioN commented on docs/platform/create-chainhook.md
> +
Missing bitcoing predicates

2023-08-08 14:54 UTC, BLuEScioN commented on docs/platform/create-chainhook.md
> +- For *Bitcoin*, the available predicate options are `txid`,`outputs`, `stacks_protocols`.
yes provided feedback

2023-08-08 16:04 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +
@BLuEScioN, Can you expand on this? I didn't get you.

2023-08-08 17:21 UTC, BLuEScioN commented on docs/platform/create-chainhook.md
> +
https://github.com/hirosystems/chainhook#:~:text=//%20Include%20proof%3A%0A%22include_proof%22%3A%20false%0A%0A//%20Include%20Bitcoin%20transaction%20inputs%20in%20payload%3A%0A%22include_inputs%22%3A%20false%0A%0A//%20Include%20Bitcoin%20transaction%20outputs%20in%20payload%3A%0A%22include_outputs%22%3A%20false%0A%0A//%20Include%20Bitcoin%20transaction%20witness%20in%20payload%3A%0A%22include_witness%22%3A%20false

2023-08-08 17:31 UTC, BLuEScioN commented on docs/platform/create-chainhook.md
> +
You don't mention these options 
// Include proof:
"include_proof": false

// Include Bitcoin transaction inputs in payload:
"include_inputs": false

// Include Bitcoin transaction outputs in payload:
"include_outputs": false

// Include Bitcoin transaction witness in payload:
"include_witness": false

2023-08-08 17:56 UTC, elenananana commented on docs/platform/create-chainhook.md
> +You'll see a navigation bar with two tabs, Contracts, and Chainhooks. Select _Chainhooks_ to create a new chainhook.
@sabbyanandan - since the tab refers to predicates, and it is the title of the tab, it should stay as is plural and capitalized "Chainhooks."

2023-08-08 18:41 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +
I will add these in the next revision as I wanted to walk through an example in this doc. Adding these at the end might be confusing with how the doc is structured.
However, I did mention that there are other options to create a chainhook. @BLuEScioN Sounds good?

2023-08-08 18:43 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +The right pane navigates to the Projects page with the Chainhooks tab open, and you can view the chainhook created.
Per Elena's comment above, the tab remains Chainhooks. Hence marking this comment as resolved.

2023-08-08 18:44 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +You'll see a navigation bar with two tabs, Contracts, and Chainhooks. Select _Chainhooks_ to create a new chainhook.
Marking this comment as resolved as there is no further change required.

2023-08-08 18:44 UTC, LakshmiLavanyaKasturi commented on docs/platform/create-chainhook.md
> +- For *Bitcoin*, the available predicate options are `txid`,`outputs`, `stacks_protocols`.
Thanks!

2023-08-08 18:57 UTC, merged

2023-08-08 18:59 UTC, BLuEScioN approved these changes