feat: add platform ssh docs
hirosystems/docs pull request #469
Opened 2023-09-20 13:04 UTC by beguene

This is a draft version of the documentation for the platform ssh or how to setup a local editor for the Hiro Platform.
Not to be merged yet as the feature is not yet released on the platform.

2023-09-20 15:01 UTC, sabbyanandan requested changes
This is looking great! I left a few suggestions. We could also add the screenshots when they are ready.

2023-09-20 15:01 UTC, sabbyanandan commented on docs/platform/setting-up-local-editor.md
> +First, you need to check if you already have an existing SSH key on your device. This is often located in `~/.ssh/id_ed25519.pub`. You can view your SSH keys by running the following command in your
To be consistent with the rest of the Platform guides, perhaps we can remove the `Step X`?

2023-09-25 15:28 UTC, andresgalante commented
@mefrem would you be able to review this one, please?

2023-09-26 14:59 UTC, ryanwaits commented on docs/platform/connect-desktop-to-cloud.md
> +Next, you'll provide your public key to the Hiro Platform. You can do this by copying your public key and pasting it into the SSH Public Key field in the Hiro Platform.
might be nice to add a code snippet for how to copy pk, ex:

for mac: ```cat ~/.ssh/id_rsa.pub | pbcopy```

also, where in the platform would someone find where to paste in the public key? i did a quick check and wasn't sure where to add it.

2023-09-26 15:01 UTC, ryanwaits commented on docs/platform/connect-desktop-to-cloud.md
> +Replace `<your-workspace-url>` with the actual URL of your pod, which should look something like this: https://4a1b57d0c473.platform.hiro.so/
maybe add some context on how to find the unique pod url, ie you must open a specific project in the editor to find it (unless theres somewhere else in the app where you can find)

2023-10-10 13:04 UTC, beguene commented on docs/platform/connect-desktop-to-cloud.md
> +Next, you'll provide your public key to the Hiro Platform. You can do this by copying your public key and pasting it into the SSH Public Key field in the Hiro Platform.
I added for Linux, Mac and Windows and a short phrase and a direct link to the settings (where the user can add the ssh keys)

2023-10-12 10:02 UTC, beguene commented
@andresgalante @ryanwaits Shall I merge this ?

2023-10-17 13:45 UTC, beguene commented
@sabbyanandan I made the changes you requested, but I can't merge it until you approve. Let me know if there are still things missing.

2023-10-17 15:41 UTC, sabbyanandan requested changes

2023-10-17 15:41 UTC, sabbyanandan commented on docs/platform/connect-desktop-to-cloud.md
> +To enable SSH access and Git authentication to your Hiro Platform workspace, you'll need to add the following lines to your `~/.ssh/config` file:
Aside from the instructions, do we want to explain what this does? This is so that users are aware of copying this command into their machine (with root access).

2023-10-17 15:41 UTC, sabbyanandan commented on docs/platform/connect-desktop-to-cloud.md
> +To create an SSH connection to your Hiro Platform workspace you will need your workspace url. To find it just go to [https://platform.hiro.so/projects](https://platform.hiro.so/projects) and click on
```suggestion
To create an SSH connection to your Hiro Platform workspace you will need your workspace url. To find it just go to [https://platform.hiro.so/projects](https://platform.hiro.so/projects) and click on `Connect Your Local Editor`. You will find your workspace url at the bottom.
```

2023-10-17 15:41 UTC, sabbyanandan commented on docs/platform/connect-desktop-to-cloud.md
> +Visual Studio Code (VSCode) has built-in support for SSH connections, allowing you to connect to and work on your remote server directly from your local VSCode environment. Here's how to set it up:
The user still has to install "Remote-SSH" extension if they don't have it already, though. So I would rephrase this language.

2023-10-17 15:41 UTC, sabbyanandan commented on docs/platform/connect-desktop-to-cloud.md
> +3. Type "Remote-SSH: Connect to Host..." and select it from the dropdown list.
If this extension is not available already, user must install it.

2023-10-17 16:36 UTC, sabbyanandan approved these changes
Let's go!

2023-10-18 05:50 UTC, merged