add ordhook docs
hirosystems/docs pull request #514
Opened 2023-10-03 15:57 UTC by ryanwaits

Adding Ordhook documentation to sidebar

2023-10-03 16:40 UTC, sabbyanandan requested changes
A few subtle change-edits and nits. 

More importantly, you are pulling the remote files correctly, but there are also some local changes to the pulled files, which can be double-checked to be sure.

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/getting-started.md
> +title: Getting Started
A meta-comment:

It might be a good idea to update the README with these instructions and then pull the README into the docs here. You can look at this approach in action for Clarinet for reference.

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-explore-ordinal-activities.md
> +Ordhook can be used to extract ordinal activities from the Bitcoin chain and stream these activities to the indexer. This guide helps you with the steps to explore ordinal activities and post these a
The "indexer" part, while it is understandable by us, I doubt the general audience would. 

We could either describe the indexer beforehand or explain downstream step more generally (e.g., building your database)

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-explore-ordinal-activities.md
> +This section walks you through streaming ordinal activities to an indexer. To post the ordinal activity, you'll need to configure bitcoind. Refer to [Setting up a bitcoin node](https://docs.hiro.so/c
Because "bitcoind" is required for Ordhook, it would be good to have explicit instructions in this document or reuse the same MD file/content in both Chainhook and Ordhook.

I say this because, once the developer context switches to Chainhook, the information fidelity might be lost, and there's no direct way to get back to Ordhook other than clicking the "back" buttons.

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-explore-ordinal-activities.md
> +This section walks you through streaming ordinal activities to an indexer. To post the ordinal activity, you'll need to configure bitcoind. Refer to [Setting up a bitcoin node](https://docs.hiro.so/c
If it is a bigger chunk of work to get it done as part of this PR, the cross-link reference is fine for now, and we can improve the extraction+reuse in a different PR.

Just listing a few suggestions.

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +In this section, you'll learn how to run Ordhook as a service using [Chainhook SDK](https://github.com/hirosystems/chainhook/tree/develop/components/chainhook-sdk) to create a predicate ordinal theor
The "create a predicate ordinal theory" language could be hard to follow. We could consider rephrasing this so our audience can understand it.

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +- Configure ordhook by following [this](./how-to-explore-ordinal-activities.md#configure-ordhook) section
```suggestion
- Configure Ordhook by following [this](./how-to-explore-ordinal-activities.md#configure-ordhook) section
```

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +Use the following command to start the ordhook service for streaming and processing new blocks appended to the Bitcoin blockchain.
```suggestion
Use the following command to start the Ordhook service for streaming and processing new blocks appended to the Bitcoin blockchain.
```

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +When the ordhook service starts, the chainhook service gets initiated in the background to augment the blocks that Bitcoind sends. The bitcoind sends zeromq notifications to Ordhook to retrieve the i
```suggestion
When the Ordhook service starts, the chainhook service gets initiated in the background to augment the blocks from Bitcoin. Bitcoind sends ZeroMQ notifications to Ordhook to retrieve the inscriptions.
```

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +When the ordhook service starts, the chainhook service gets initiated in the background to augment the blocks that Bitcoind sends. The bitcoind sends zeromq notifications to Ordhook to retrieve the i
To use Ordhook, we do not need Chainhook, but just a Bitcoin node. At least that is my interpretation. I can stand corrected, though.

@lgalabru: Thoughts?

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +To enable dynamically posting endpoints to the server, you can spin up the redis server by enabling the following lines of code in the `ordhook.toml` file.
```suggestion
To enable dynamically posting endpoints to the server, you can spin up the Redis server by enabling the following lines of code in the `ordhook.toml` file.
```

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +To enable dynamically posting endpoints to the server, you can spin up the redis server by enabling the following lines of code in the `ordhook.toml` file.
This statement can be explained with why Redis is required to expose RESTful endpoints.

2023-10-03 16:40 UTC, sabbyanandan commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +A comprehensive OpenAPI specification explaining how to interact with this HTTP REST API can be found [here](https://github.com/hirosystems/chainhook/blob/develop/docs/chainhook-openapi.json).
This is pointing to the spec file in Chainhook repo, is it expected?

2023-10-03 16:40 UTC, sabbyanandan commented on docusaurus.config.js
> +        documents: ['getting-started.md', 'overview.md'],
Oh wait. You are pulling the remote files!

2023-10-03 17:11 UTC, ryanwaits commented on docs/ordhook/how-to-guides/how-to-explore-ordinal-activities.md
> +This section walks you through streaming ordinal activities to an indexer. To post the ordinal activity, you'll need to configure bitcoind. Refer to [Setting up a bitcoin node](https://docs.hiro.so/c
this is good feedback, appreciate it!

2023-10-03 17:12 UTC, ryanwaits commented on docusaurus.config.js
> +        documents: ['getting-started.md', 'overview.md'],
ha yeah i started with local files, wasn't sure if they would get pulled in to test out locally but then i figured they would just get it overwritten with any changes from the remote repo

2023-10-03 17:14 UTC, ryanwaits commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +A comprehensive OpenAPI specification explaining how to interact with this HTTP REST API can be found [here](https://github.com/hirosystems/chainhook/blob/develop/docs/chainhook-openapi.json).
yeah i believe that is the only reference to the openapi spec, but i could copy/paste that and create a new `ordhook-openapi.json` file to avoid the confusion

2023-10-04 14:18 UTC, lgalabru commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +When the ordhook service starts, the chainhook service gets initiated in the background to augment the blocks that Bitcoind sends. The bitcoind sends zeromq notifications to Ordhook to retrieve the i
You're correct @sabbyanandan!

2023-10-04 14:18 UTC, lgalabru commented on docs/ordhook/how-to-guides/how-to-use-ordhook-as-a-service-using-bitcoind.md
> +When the ordhook service starts, the chainhook service gets initiated in the background to augment the blocks that Bitcoind sends. The bitcoind sends zeromq notifications to Ordhook to retrieve the i
Ordhook is embedding `chainhook-sdk`

2023-10-04 15:47 UTC, lgalabru commented on docs/ordhook/getting-started.md
> +Ordhook is a utility designed for interacting with the [Ordinal Theory](https://trustmachines.co/glossary/ordinal-theory) protocol, enabling you to assign distinct identifiers to newly minted satoshi
`utility`: `tool`? `command line tool`? `developer tool`?

2023-10-04 18:15 UTC, ryanwaits commented on docs/ordhook/getting-started.md
> +cargo ordhook-install
updates here: https://github.com/hirosystems/ordhook/pull/184

2023-10-04 18:15 UTC, ryanwaits commented on docs/ordhook/getting-started.md
> +Ordhook is a utility designed for interacting with the [Ordinal Theory](https://trustmachines.co/glossary/ordinal-theory) protocol, enabling you to assign distinct identifiers to newly minted satoshi
updates here: https://github.com/hirosystems/ordhook/pull/184

2023-10-04 18:53 UTC, sabbyanandan requested changes
@ryanwaits: Your assembly of remote docs from https://github.com/hirosystems/ordhook/tree/develop/docs and the related config changes looks good; however, I am confused as to why you would want the `overview.md` and `getting-started.md` files locally also. 

They are at the upstream repo, anyway: https://github.com/hirosystems/ordhook/tree/develop/docs

I think simply pointing to those files where the remote plugin dumped in the `sidebar.js` is all you would need. 

I could be misinterpreting, and I am on standby to be corrected.

2023-10-04 20:12 UTC, ryanwaits commented
yeah that's nbd, i deleted them locally and will have them ignored by git moving forward

otherwise i think these updates should be in a good spot to go ahead and publish, lmk if we're good to approve!

2023-10-04 20:15 UTC, sabbyanandan approved these changes
Heck yeah! Looks good now. Thanks, @ryanwaits!

2023-10-04 22:03 UTC, merged