feat(devnet-docs): added docs for devnet'
hirosystems/docs pull request #561
Opened 2023-11-06 23:59 UTC by BLuEScioN

## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?
We are releasing devnet for platform soon. These docs are documenting this new feature
3. What was changed?
Just new docs
5. Link to relevant issues?

## Checklist

- [ X] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ X] New links to files and images were verified
- [ X] For fixes/refactors: all existing references were identified and replaced
- [ X] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ X] Clear code samples were provided
- [ X] People were tagged for review

2023-11-07 14:38 UTC, ryanwaits commented
this lgtm on paper - however since the feature is not live i cant follow along with the guide to verify everything is accurate...

will wait for this feature to be merged and revisit 🙏

2023-11-07 14:41 UTC, ryanwaits requested changes
minor typo fix

2023-11-07 14:41 UTC, ryanwaits commented on docs/platform/devnet.md
> +With Devnet active, clicking on the status pill again will present the option to 'View Devnet Details'. Selecting this takes you to the Devnet dashboard, where you can interact with a block explorer
```suggestion
With Devnet active, clicking on the status pill again will present the option to 'View Devnet Details'. Selecting this takes you to the Devnet dashboard, where you can interact with a block explorer and an "assembly line" of mined blocks. Transactions within each block are accessible here, and a search function is available for efficient block navigation.
```

2023-11-07 14:41 UTC, ryanwaits commented on docs/platform/devnet.md
> +With Devnet active, clicking on the status pill again will present the option to 'View Devnet Details'. Selecting this takes you to the Devnet dashboard, where you can interact with a block explorer
just a typo on spacing

2023-11-07 20:49 UTC, BLuEScioN commented
> this lgtm on paper - however since the feature is not live i cant follow along with the guide to verify everything is accurate, is there a sandbox environment that i can be using?
> 
> otherwise will wait for this feature to be merged and revisit 🙏

We are trying to test on platform.dev.hiro.so, however there is a bug currently that is breaking devnet atm. I can let you know once that is fixed and you can inspect the new feature yourself. Probably tomorrow

2023-11-09 16:44 UTC, ryanwaits commented
everything checks out nicely on `platform.dev.hiro.so` ✨

2023-11-09 17:12 UTC, ryanwaits approved these changes

2023-11-10 20:37 UTC, andresgalante commented
We;'ll merge this when we release the feature

2023-11-16 20:43 UTC, merged