nakamoto updates
hirosystems/docs pull request #636
Opened 2024-03-20 15:38 UTC by ryanwaits

## What does this PR do?

- [ ] add a banner and call to action that points to new nakamoto updates page
- [ ] create a new nakamoto updates page with a changelog for all products
- [ ] add a sidebar item for this new page

2024-03-20 19:19 UTC, ryanwaits commented
in addition, ran into some odd build issues with some formatting in the stacks.js markdown files, so i reformatted a few lines and changed the extensions to use `.mdx` instead of `.md` which seems to have solved the issue.

...in case anyone is wondering why the diff is larger than expected.

2024-03-21 15:42 UTC, diwakergupta commented
> observing an issue with our layout pages that should render banners post `docusaurus 3` version upgrade, and having trouble figuring out what the breaking change was and why they aren't showing up. for now ill commit the version back to `2.4.3` since this shouldn't break any existing updates since then

hmm, feels like a pretty big hammer (reverting back to docusaurus 2) for this one nail. can you do just the changelog and sidebar for now, I'm happy to dig into the banner issue separately. that way you needn't block on downgrading the whole thing.

2024-03-21 18:10 UTC, ryanwaits commented
> can you do just the changelog and sidebar for now

yeah that's fine with me if we're cool without the banner

i also wouldn't drain too much energy on the banner issue in v3, i already wasted enough 😆

2024-03-25 17:11 UTC, ryanwaits commented
my guess is the `linkcheck` is failing because of a reference to the new `/nakamoto-api` endpoint so should fix itself when merged

2024-03-25 18:30 UTC, saralab commented on docs/nakamoto/stacks-api.mdx
> +### Nakamoto endpoints
Include the Nakamoto Testnet URL here? https://api.nakamoto.testnet.hiro.so/

2024-03-25 18:35 UTC, andresgalante requested changes

2024-03-25 18:35 UTC, andresgalante commented on docs/nakamoto/index.mdx
> +**[Add image of the new blocks view]**
@ryanwaits let's use this image here

![image_720](https://github.com/hirosystems/docs/assets/1832037/67242ac5-b53b-4158-9818-ec29e9669b81)

2024-03-25 18:35 UTC, andresgalante commented on docs/nakamoto/index.mdx
> +**[Add image of the view selector]**
We can use this image here

![image_720-1](https://github.com/hirosystems/docs/assets/1832037/cd186d11-5b89-4422-bade-8d457a0c0be9)

2024-03-25 18:35 UTC, andresgalante commented on docs/nakamoto/index.mdx
> +2. **COMING SOON: Grouped by Bitcoin Block:** Shows BTC blocks flow alongside STX blocks. (coming soon)
You are mentioning "coming soon" twice

2024-03-25 18:35 UTC, andresgalante commented on docs/nakamoto/index.mdx
> +**[Add image of the live view selector]**
please remove this line

2024-03-25 18:37 UTC, andresgalante commented on docs/nakamoto/explorer.mdx
> +## What's New
Lets make here the same changes we are doing to the index.mdx

2024-03-25 18:48 UTC, rafaelcr approved these changes
LGTM for the API doc changes

2024-03-25 19:03 UTC, hugocaillard approved these changes
LGTM 👍 
Thanks @ryanwaits!

2024-03-25 19:05 UTC, andresgalante approved these changes
Thanks for the changes

2024-03-25 19:22 UTC, smcclellan commented on docs/nakamoto/clarinet.mdx
> +Do not expect to reach Epoch 3.0 with Clarinet 2.4.0. This release is focusing on Epoch 2.4.
```suggestion
Do not expect to reach Epoch 3.0 with Clarinet 2.4.0. This release is focusing on Epoch 2.5.
```

2024-03-25 19:31 UTC, smcclellan approved these changes
These are formatting improvements -- otherwise looks great!

2024-03-25 19:31 UTC, smcclellan commented on docs/nakamoto/clarinet.mdx
> +Using one of you Clarinet projects, or a new one (with `clarinet new nakamoto-project`), update the
```suggestion
Using one of your Clarinet projects, or a new one (with `clarinet new nakamoto-project`), update the
```

2024-03-25 19:31 UTC, smcclellan commented on docs/nakamoto/clarinet.mdx
> +Under the `[devnet]` section, set `use_nakamoto = true`, the `pox-4.clar` contract should be
```suggestion
Under the `[devnet]` section when `use_nakamoto = true` is set, the `pox-4.clar` contract should be
```

2024-03-25 19:31 UTC, smcclellan commented on docs/nakamoto/index.mdx
> +- Running clarinet check --enable-clarity-wasm now runs the current interpreter and  clarity wasm  side-by-side to allow comparing outputs.
```suggestion
- Running `clarinet check --enable-clarity-wasm` now runs the current interpreter and clarity wasm side-by-side to allow comparing outputs.
```

2024-03-25 19:31 UTC, smcclellan commented on docs/nakamoto/index.mdx
> +- clarinet console now automatically runs the current interpreter and clarity wasm side-by-side and logs any difference in outputs.
```suggestion
- `clarinet console` now automatically runs the current interpreter and clarity wasm side-by-side and logs any difference in outputs.
```

2024-03-25 19:31 UTC, smcclellan commented on src/components/_content.ts
> +    text: ['The Nakamoto upgrade is now live on testnet: see a list of Hiro product changes here.'],
```suggestion
    text: ['The Nakamoto upgrade is now live on Testnet! See a list of Hiro product changes here.'],
```

2024-03-25 19:33 UTC, ryanwaits commented
> These are formatting improvements -- otherwise looks great!

thanks @smcclellan !

2024-03-25 19:36 UTC, andresgalante requested changes

2024-03-25 19:36 UTC, andresgalante commented on docs/nakamoto/explorer.mdx
> +This new view is available on [Nakamoto Testnet](https://explorer.hiro.so/?chain=testnet&api=https://api.nakamoto.testnet.hiro.so/), accessible via the Network dropdown.
@ryanwaits can we remove the trailing / here please

2024-03-25 19:38 UTC, andresgalante commented on docs/nakamoto/index.mdx
> +This new view is available on [Nakamoto Testnet](https://explorer.hiro.so/?chain=testnet&api=https://api.nakamoto.testnet.hiro.so/), accessible via the Network dropdown.
and here, lets remove the trailing `/`

2024-03-25 19:41 UTC, andresgalante approved these changes

2024-03-25 21:20 UTC, merged