Guide for observing a contract_call predicate with Chainhook and extracting data from its payload
hirosystems/docs pull request #723
Opened 2024-07-30 04:33 UTC by natebuch

## Description
There is very little information on the payload that Chainhook returns.  This guide walks through the creation of contract_call predicate for a basic voting contract and then examines points if interest in the associated Chainhook payload.

To support this guide:
1.  A .json file for the payload has been added in the public folder as a full example reference point.
2. A resources folder was added to the chainhook folder with the simple-vote.mdx file.  This is imported as a code example into the guide.
3. Links to other resources within doc and externally were verified.

2024-07-30 04:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hirosystems/docs?pullRequest=723) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hirosystems/docs?pullRequest=723) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hirosystems/docs?pullRequest=723) it.</sub>

2024-07-30 21:30 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +description: Learn how to use Chainhook to observe contract calls on the Stacks blockchain
```suggestion
description: Learn how to use Chainhook to observe smart contract calls.
```

2024-07-30 21:37 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +The `contract_call` predicate scope is designed to allow you to use Chainhook to observe direct functions calls within a smart contract. The payload returned by Chainhook will contain transaction dat
```suggestion
The `contract_call` predicate scope is designed to target direct function calls within a smart contract. When triggered, Chainhook will return a payload with transaction data detailing the on-chain events contained in these functions.
```

2024-07-30 21:38 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +By designing your smart contract functions in conjunction with your data source and use case, Chainhook and `contract_call` can become an excellent tool for monitoring interactions with critical cont
this paragraph is a bit confusing, perhaps its unneeded or needs to be re-worded?

2024-07-30 21:41 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +The `predicate` json object is the primary tool for interacting with the Chainhook data indexer. Chainhook will evaluate our `predicate` to determine what blockchain, network and scope it will use to
```suggestion
The `predicate` is your main interface for querying the Chainhook data indexer. Chainhook uses your specified `predicate` to select the appropriate blockchain, network, and scope for monitoring transactions.
```

2024-07-30 21:43 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +You can view the full predicate example will be using in this guide below.
```suggestion
You can view the full predicate example we will be using in this guide below.
```

2024-07-30 21:47 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +Finally, we will define how Chainhook should deliver its data payload when it is triggered by our `predicate` within the `then_that` specification.
```suggestion
Finally, you need to define how Chainhook delivers the payload when it is triggered by our `predicate` within the `then_that` specification.
```

2024-07-30 21:47 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +When using `file_append`, we specify the `path` we want Chainhook to write its data payload to.
```suggestion
When using `file_append`, specify the `path` you want Chainhook to post the payload data to.
```

2024-07-30 21:49 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +Now that we have built our Stacks blockchain `predicate`, we are ready to use Chainhook to scan for blocks that match our `contract_call` scope and view the payload it returns. Whenever this method i
```suggestion
With our `predicate` set up, we can now use Chainhook to monitor blocks that match our `contract_call` scope and analyze the returned payload. Chainhook will track events where this function is directly invoked in a transaction and generate a detailed payload containing transaction data at the block level.
```

2024-07-30 21:54 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +If you previously installed Chainhook, we will specify our `contract-call-chainhook.json` predicate file in the following command to scan the Stacks blockchain.
> If you previously installed Chainhook

this feels a bit redundant, given that installation has been called out as a requirement. i would assume the reader is following the guide and carry on with the instructions, which i think helps maintain focus and continuity.

2024-07-30 21:55 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +With our `transaction` object returned, let's start looking at some of the important data elements we can derive from it. The first element `transcation_identifier` is straightforward, containing a h
```suggestion
Once the `transaction` object is returned, we can begin examining important data elements it contains. The first element, `transaction_identifier`, includes a hash value that uniquely identifies our transaction.
```

2024-07-30 21:57 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +The next element we will look for data related to our `contract_call` is the `metadata` object and its children elements. Since we are looking to build out our data source, knowing the success state
```suggestion
Next, focus on the `metadata` object within our `contract_call` data. It's crucial to determine the success state of our transaction. Chainhook captures and reports on transactions regardless of their outcome. Utilize the `success` object to assess transaction success. Additionally, extract the sender of the transaction and the `result` returned by the contract.
```

2024-07-30 21:58 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +Next, we will look at our `kind` object and its elements. Within the `data` object, we find data related to the contracts our function exists on as a value of `contract_identifier`, the function call
```suggestion
Moving forward, examine the `kind` object and its components within your `contract_call`. The data object contains crucial information: `contract_identifier` specifies the contract our function resides on, `method` identifies the function called, and `args` lists the arguments passed when invoking this function. In our case, the `cast-vote` function accepts no arguments, resulting in an empty `args` array.
```

2024-07-30 21:59 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +The next element we will look for data related to our `contract_call` is the `metadata` object and its children elements. Since we are looking to build out our data source, knowing the success state
```suggestion
Next, focus on the `metadata` object within your `contract_call` data. It's crucial to determine the success state of your transaction. Chainhook captures and reports on transactions regardless of their outcome. Utilize the `success` object to assess transaction success. Additionally, extract the sender of the transaction and the `result` returned by the contract.
```

2024-07-30 22:03 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +The last element of the `metadata` object we will examine is the `receipt` object and its `events` array and its object elements. In our `contract_call` example, the information we want to pull into
```suggestion
The final element to analyze in the `metadata` object is the `receipt` object, particularly its `events` array and the objects within it.

For your `contract_call`, the relevant data is housed in the `data` object of these elements. Similar to the `kind` object, our `data` object includes a `contract_identifier` key, which in this case is linked to the `simple-vote-v0` contract.

Since you are using the `print` statement to return data from your contract's `cast-vote` function, the `events` array will contain `topic` and `value` keys.

The `topic` indicates that the print statement is being used to output data, while the `value` key will display the specific data set within that `print` function.
```

2024-07-30 22:05 UTC, ryanwaits commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +Now that we have identified where the relevant data lives in the Chainhook payload, you can build the necessary logic into your API to extract it. You should be able to build a data source for your D
```suggestion
Now that you've located the relevant data in the payload, you can start to extract the relevant information into your API.

The following is an example of how you might store your information in a database table:
```

2024-07-30 22:08 UTC, ryanwaits requested changes
hey @natebuch this is such a needed piece of content, really appreciate the contribution!

i've left a bunch of small edits, lmk if you have any questions, but overall this is looking great and i think we should be able to merge this in with a few more adjustments

2024-07-30 23:25 UTC, natebuch commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +By designing your smart contract functions in conjunction with your data source and use case, Chainhook and `contract_call` can become an excellent tool for monitoring interactions with critical cont
Resolved in latest commit.

2024-07-30 23:25 UTC, natebuch commented on content/docs/stacks/chainhook/guides/observing-contract-calls.mdx
> +If you previously installed Chainhook, we will specify our `contract-call-chainhook.json` predicate file in the following command to scan the Stacks blockchain.
Resolved in latest commit.

2024-07-31 02:11 UTC, ryanwaits approved these changes

2024-07-31 20:40 UTC, closed without merging