Update running-testnet-node.md
hirosystems/docs pull request #75
Opened 2022-03-22 06:50 UTC by LakshmiLavanyaKasturi

## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?
2. What was changed?
3. Link to relevant issues?

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [ ] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

2022-03-31 12:06 UTC, LakshmiLavanyaKasturi commented
@pgray-hiro: Could you review my PR? Thanks.

2022-04-01 22:27 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: Could you review my edits. Thanks.

2022-04-02 14:10 UTC, sabbyanandan requested changes

2022-04-02 14:10 UTC, sabbyanandan commented on docs/get-started/running-testnet-node.md
> +You can open the following ports on the host machine:
The firewall configuration described in this section is a requirement. In other words, the ports must be open and accessible for the node to receive and sync data.

Considering that, it'd be better to state the explicit requirement as-is. Perhaps: "The following ports must be open on the host machine:"

2022-04-03 20:22 UTC, LakshmiLavanyaKasturi commented on docs/get-started/running-testnet-node.md
> +You can open the following ports on the host machine:
Sounds good!

2022-04-05 20:35 UTC, sabbyanandan approved these changes
LGTM

2022-04-05 20:36 UTC, merged