Update testing-contracts.md
hirosystems/docs pull request #81
Opened 2022-04-01 22:21 UTC by LakshmiLavanyaKasturi

Small wording changes to improve readability of the article.

## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?
2. What was changed?
3. Link to relevant issues?

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [ ] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

2022-04-01 22:24 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: Could you review my edits to improve readability of the article. Thanks.

2022-04-02 14:05 UTC, sabbyanandan requested changes
Thanks again. A couple of suggestions; otherwise, LGTM.

2022-04-02 14:05 UTC, sabbyanandan commented on docs/tutorials/testing-contracts.md
> +The project resources are created in your current folder. Take note of the `contracts` and `test` folders. The other files are standardized pieces to wire up the project.
This may help make the last sentence clearer.

```suggestion
The project resources are created in your current folder. Take note of the `contracts` and `test` folders. The other files are standardized components required to run the project.
```

2022-04-03 02:53 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: Committed the requested changes. PR should be ready to merge. Thanks.

2022-04-05 20:34 UTC, sabbyanandan approved these changes
LGTM

2022-04-05 20:35 UTC, merged