Update clarinet.md
hirosystems/docs pull request #88
Opened 2022-04-20 06:41 UTC by LakshmiLavanyaKasturi

- Re-worded sentences for clarity
- Added bulleted list

## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?
2. What was changed?
3. Link to relevant issues?

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [ ] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

2022-04-20 06:47 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: Please review my changes. Thanks.

2022-04-21 23:49 UTC, sabbyanandan requested changes
Thanks, @LakshmiLavanyaKasturi.

2022-04-21 23:49 UTC, sabbyanandan commented on docs/smart-contracts/clarinet.md
> +- Clarity REPL.
nit: `.` probably not necessary

2022-04-21 23:49 UTC, sabbyanandan commented on docs/smart-contracts/clarinet.md
> +When developing smart contracts, you can use the [Clarity Visual Studio Code plugin][].
```suggestion
When developing smart contracts, you can also use the [Clarity Visual Studio Code plugin][].
```

.. just so that the optionality is presented

2022-06-28 21:17 UTC, LakshmiLavanyaKasturi commented
@sabbyanandan: Can I go ahead and merge these changes?

2022-06-28 21:53 UTC, merged